apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: logistics-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: APP_ENV
              value: "{{ .Values.environment }}"
            - name: DB_HOST
              value: "{{ .Release.Name }}-postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: logistics
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: postgres