apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-postgres
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}