services:

  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: logistics-app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: logistics-postgres
    environment:
      POSTGRES_DB: logistics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: