replicaCount: 1

image:
  repository: 470024785854.dkr.ecr.us-east-1.amazonaws.com/dev/logistics
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5000

environment: production

postgres:
  image: postgres:16
  port: 5432
  database: logistics
  username: postgres
  password: postgres