apiVersion: v1
kind: Service
metadata:
  name: logistics-app
  namespace: logistics
spec:
  selector:
    app: logistics-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30080
  type: NodePort