name: Logistics CI/CD

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:

  CI:
    uses: ./.github/workflows/reusable-ci.yml

    with:
      aws-region: "us-east-1"
      ecr-repository: "dev/logistics"

    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


  CD:
    needs: CI

    uses: ./.github/workflows/reusable-cd.yml

    with:
      aws-region: "us-east-1"
      ecr-repository: "dev/logistics"
      eks-cluster-name: "logistics-eks"
      helm-release: "logistics"
      helm-chart: "./helm/logistics"

      image-tag: ${{ github.sha }}
      image-uri: 470024785854.dkr.ecr.us-east-1.amazonaws.com/dev/logistics:${{ github.sha }}

    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}